### ISSUE TITLE
提几个意见

### ISSUE THREAD

**Issue by egrcc** [wuzhouhui/awk#2]
首先感谢翻译以及制作了精美的pdf，阅读过程中发现了一些小问题。

![img_20160224_17480625](https://cloud.githubusercontent.com/assets/6469953/13281527/56dfcff4-db1f-11e5-87c5-584606deb55d.JPG)

这里没有对齐，我看原书是对齐的。

![img_20160224_17491855](https://cloud.githubusercontent.com/assets/6469953/13281534/64b14b30-db1f-11e5-8536-b0dd3f89f28e.JPG)

这里应为 expression。

![img_20160224_17495599](https://cloud.githubusercontent.com/assets/6469953/13281538/672910a0-db1f-11e5-9f7c-45e76c043d95.JPG)

这里的翻译语序我感觉应该要有所调整，以更符合中文的表达习惯。原书中有多处，这里只是一个例子。

**Comment by wuzhouhui** [comment]
已修改, 谢谢指正.
像你说的这些问题, 只能靠细心的读者来发现了.
