### ISSUE TITLE
支票日期和原文不同

### ISSUE THREAD

**Issue by marjune163** [wuzhouhui/awk#20]
支票日期和原文不同，虽然不影响阅读。不知道是否有必要统一下？
https://github.com/wuzhouhui/awk/blob/881807c18dff44db9832aae2c4a89ec36b8f4290/latex_src/data_processing.tex#L401

**Comment by wuzhouhui** [comment]
支票的内容是当时运行 awk 程序的输出, 为了保证输出的完整性, 我尽量不对输出进行手工调整.
