### ISSUE TITLE
PDF 能否有6寸的排版

### ISSUE THREAD

**Issue by ammzen** [wuzhouhui/awk#3]
有幸看到大侠的中译本，LaTeX 排版太漂亮了，电脑上看起来很舒服，再次感谢！
因平时想装在 kindle 上来看，想问一下能否提供6寸 kindle 大小的文件？

**Comment by wuzhouhui** [comment]
Kindle 的 6 寸版面比通常的印刷纸张小太多, 刚才试了一下, 得到的排版简直不能看. 在代码中有很多地方我都是用的硬编码, 特别是画图部分, 因此没办法通过简单地修改版面尺寸来得到 Kindle 的 6 寸格式, 需要修改的地方太多了, 我也没办法面面俱到, 仓库中的 PDF 主要是为了在电脑上阅读与印刷, 当初并没有考虑太多其他设备.

**Comment by xpqiu** [comment]
提供了一个ipad版，版式没有优化，可以将就了看：）
