### ISSUE TITLE
怎么不开个捐赠？

### ISSUE THREAD

**Issue by luoyesiqiu** [wuzhouhui/awk#37]

**Comment by wuzhouhui** [comment]
我翻译这本书的主要目的是为了分享知识, 而且严格来说像我这种私自翻译并传播好像已经侵权了, 我可不想惹麻烦, 见 https://github.com/EbookFoundation/free-programming-books/pull/1580

**Comment by luoyesiqiu** [comment]
@wuzhouhui  好吧，祝你好运

**Comment by luoyesiqiu** [comment]
谢谢你的无偿翻译
