### ISSUE TITLE
是否可以把二进制文件放在github release部分释出

### ISSUE THREAD

**Issue by lingr7** [wuzhouhui/awk#38]
用git来管理PDF这种二进制文件，很麻烦。

**Comment by wuzhouhui** [comment]
PDF 更新很不频繁, 为了方便那些没有安装 LaTeX 的读者, 所以把 PDF 加到了版本库里. 没听说过 GitHub Release 这东西.

**Comment by lingr7** [comment]
https://github.com/wuzhouhui/awk/releases 就是这个啊。
https://github.com/texstudio-org/texstudio/releases/tag/3.1.1
![image](https://user-images.githubusercontent.com/37898999/110591944-a1962480-81b4-11eb-9953-92219d557634.png)
这是由维护者决定的，可以放出一些二进制文件。一般是由定档源代码编译好的程序安装包。

**Comment by wuzhouhui** [comment]
下次试试
