### ISSUE TITLE
勘误 - 多了个'当'字

### ISSUE THREAD

**Issue by zhuqifu** [wuzhouhui/awk#41]
你们好，感谢你们的翻译。

在23页的正下方

'''**当当**前输入行包含一段能够被 regexpr 匹配的子字符串时, 该模式被匹配.'''
\------

这里多了个'当'字。

谢谢

**Comment by wuzhouhui** [comment]
这不是笔误, 断句的地方是
"当   当前输入行..."
不过, 你有此疑问, 说明原来的翻译不太好, 稍微调整下.
