### ISSUE TITLE
原书第六章 136 页， 倒数第6行

### ISSUE THREAD

**Issue by rced** [wuzhouhui/awk#42]
The output operations have been written as separate functions to localize changes for specific devices.
您的翻译：
输出操作被分散在若干个函数中, 这样的话, 即使以后要为特定的设备对代码进行修改, 也可以把修改局限在小范围内.

建议修改为：
输出操作封装在独立的函数中，其中的代码与具体设备打交道

**Comment by rced** [comment]
类似的译文109页中
...我们把提取第一个属性值的代码局限在函数prefix 中...
局限在建议翻成封装在

**Comment by wuzhouhui** [comment]
采纳了部分建议, 谢谢.

**Comment by rced** [comment]
感谢您的翻译，这工作非常有意义。弱弱地问下，翻译前您有取得作者的授权，或者中译版的版权吗？
