### ISSUE TITLE
文中的句号是否应当采用中文句号『。』

### ISSUE THREAD

**Issue by MrCoder** [wuzhouhui/awk#46]
目前文中的句号采用的是英文的实心圆点『.』。是否应该采用中文句号『。』？

**Comment by wuzhouhui** [comment]
个人习惯, 技术书籍我喜欢一律使用英文标点. 因为中英文混排时, 有时候很难决定应该用中文标点还是英文标点, 而且混合使用两种标点看起来很难看. 为了方便, 我就统一使用英文标点了.

**Comment by MrCoder** [comment]
谢谢你的解释。我关闭这个Issue了。
